In [70]:
import warnings
warnings.filterwarnings("ignore")

In [71]:
import os
import torch
import numpy as np
import pandas as pd

from flonacomldft.utils.io_utils import (
    load_pickle_file,
    get_project_path
)

from flonacomldft.internal_coordinates import (
    Coordinates_mapping
)

from flonacomldft.utils.diagnostics import R_hat

In [72]:
methods = ['adaptive', 'mixture_model']

In [73]:
simulation_types = dict(zip( methods, [
                    ['ab-flowMC', 'ab-flowMC w.o. MLP'],
                    ['ab-flowMM', 'ab-flowMM w.o. MLP']
                ])
            )

In [74]:
simulation_types

{'adaptive': ['ab-flowMC', 'ab-flowMC w.o. MLP'],
 'mixture_model': ['ab-flowMM', 'ab-flowMM w.o. MLP']}

In [75]:
simulation_idxs = { methods[0]: { simulation_types[methods[0]][0]: {
                        0: 31959916,
                        1: 31959919
                    },

                    simulation_types[methods[0]][1]: {
                        0: 31961552,
                        1: 31961553
                    }
                },

                methods[1]: { 
                    simulation_types[methods[1]][0]: 
                        32094541,
                    simulation_types[methods[1]][1]:
                        32094594
                        
                }
            }

In [76]:
simulation_idxs

{'adaptive': {'ab-flowMC': {0: 31959916, 1: 31959919},
  'ab-flowMC w.o. MLP': {0: 31961552, 1: 31961553}},
 'mixture_model': {'ab-flowMM': 32094541, 'ab-flowMM w.o. MLP': 32094594}}

In [77]:
simulations_folders = {
    
    methods[0]: {
    simulation_types[methods[0]][0]: get_project_path() + "/2-adaptive-mlp",
    simulation_types[methods[0]][1]: get_project_path() + "/1-adaptive"
    },

    methods[1]: {
    simulation_types[methods[1]][0]: get_project_path() + "/5-multimodal-mlp",
    simulation_types[methods[1]][1]: get_project_path() + "/4-multimodal"
    }
}

save_path = get_project_path() + "/figures/preprint_v2/data"

In [78]:
simulations_folders

{'adaptive': {'ab-flowMC': '/mnt/home/amolina/ceph/adaptive-flow-mc/2-adaptive-mlp',
  'ab-flowMC w.o. MLP': '/mnt/home/amolina/ceph/adaptive-flow-mc/1-adaptive'},
 'mixture_model': {'ab-flowMM': '/mnt/home/amolina/ceph/adaptive-flow-mc/5-multimodal-mlp',
  'ab-flowMM w.o. MLP': '/mnt/home/amolina/ceph/adaptive-flow-mc/4-multimodal'}}

In [79]:
get_simulation_filename_adaptive = lambda isomer_label, idx: "results_adaptive_is{:d}_{:d}/adaptive_sampling_is{:d}_{:d}.pkl".format(
    isomer_label, idx, isomer_label, idx)
get_cvs_filename_adaptive = lambda isomer_label, idx: "results_adaptive_is{:d}_{:d}/cvs_is{:d}_{:d}.pkl".format(
    isomer_label, idx, isomer_label, idx)

In [80]:
get_simulation_filename_mm = lambda idx: "results_multimodal_sampling_mixture_{:d}/checkpoint_NA_3000.pkl".format(
    idx)
get_cvs_filename_mm = lambda idx: "cvs_temporal/cvs_slices_{:d}_3000.pkl".format(
    idx)

In [81]:
simulations_folders[methods[0]]

{'ab-flowMC': '/mnt/home/amolina/ceph/adaptive-flow-mc/2-adaptive-mlp',
 'ab-flowMC w.o. MLP': '/mnt/home/amolina/ceph/adaptive-flow-mc/1-adaptive'}

# 1. Ab-flowMC simulations

In [82]:
method = methods[0]

adaptives = {}
cvss = {}

print("Loading data...")
for simulation in simulation_types[method]:
    adaptives[simulation] = {}
    cvss[simulation] = {}
    for key, idx in simulation_idxs[method][simulation].items():
        adaptives[simulation][key] = load_pickle_file(get_simulation_filename_adaptive(key, idx), 
        simulations_folders[method][simulation])
        cvss[simulation][key] = load_pickle_file(get_cvs_filename_adaptive(key, idx),
        simulations_folders[method][simulation])
        print("Loaded adaptive sampling {:s} and cvs for isomer {:d} and idx {:d}".format(
            simulation, key, idx))

Loading data...
Loaded adaptive sampling ab-flowMC and cvs for isomer 0 and idx 31959916

Loaded adaptive sampling ab-flowMC and cvs for isomer 1 and idx 31959919
Loaded adaptive sampling ab-flowMC w.o. MLP and cvs for isomer 0 and idx 31961552
Loaded adaptive sampling ab-flowMC w.o. MLP and cvs for isomer 1 and idx 31961553

In [83]:
adaptive = adaptives[simulation_types[method][0]][0]

## 1.a Acceptance rate

In [84]:
accs_df = []

for simulation in simulation_types[method]:
    
    for key, idx in simulation_idxs[method][simulation].items():

        df = pd.DataFrame(columns=['Method', 'Isomer', 'Step', 'Acceptance Rate'])
        accs = torch.cat(adaptives[simulation][key]['accs']).float().mean(dim=1).numpy()

        df['Acceptance Rate'] = accs
        df['Isomer'] = key
        df['Step'] = np.arange(0, len(accs))
        df['Method'] = simulation

        accs_df.append(df)

accs_df = pd.concat(accs_df)
accs_df.to_csv(save_path + "/acceptance_rates.csv", index=False)
print("Acceptance rates saved to {:s}".format(save_path + "/acceptance_rates.csv"))

Acceptance rates saved to /mnt/home/amolina/ceph/adaptive-flow-mc/figures/preprint_v2/data/acceptance_rates.csv

## 1.a Collective variables and potential energy

In [85]:
cvs_us_df = []

for simulation in simulation_types[method]:
    for isomer_label in [0, 1]:

        us = torch.cat(adaptives[simulation][isomer_label]['us']).reshape(1000, 50, 1)
        cvs = cvss[simulation][isomer_label]

        cvs_us = torch.cat([us, cvs], dim=2).numpy().reshape(50000, 3)

        df = pd.DataFrame(cvs_us, columns=['U', 'C', 'R'])
        df['Isomer'] = isomer_label
        df['Method'] = simulation

        cvs_us_df.append(df)

cvs_us_df = pd.concat(cvs_us_df)
cvs_us_df.to_csv(save_path + "/cvs_potential_energy.csv", index=False)
print("CVs and potential energy saved to {:s}".format(save_path + "/cvs_potential_energy.csv"))
cvs_us_df

CVs and potential energy saved to /mnt/home/amolina/ceph/adaptive-flow-mc/figures/preprint_v2/data/cvs_potential_energy.csv

              U          C         R  Isomer              Method
0     -6.773585  10.105214  2.457276       0           ab-flowMC
1     -6.750111  10.205934  2.442652       0           ab-flowMC
2     -6.764058   9.652035  2.473082       0           ab-flowMC
3     -6.732985  10.172332  2.427748       0           ab-flowMC
4     -6.748763   9.293897  2.517407       0           ab-flowMC
...         ...        ...       ...     ...                 ...
49995 -6.704685  10.828248  2.220704       1  ab-flowMC w.o. MLP
49996 -6.746437  10.425041  2.232781       1  ab-flowMC w.o. MLP
49997 -6.714196  11.065727  2.218863       1  ab-flowMC w.o. MLP
49998 -6.743561  11.145951  2.213711       1  ab-flowMC w.o. MLP
49999 -6.659955  10.590937  2.276659       1  ab-flowMC w.o. MLP

[200000 rows x 5 columns]

## 1.c Rhat

In [86]:
rhat_df = []

for simulation in simulation_types[method]:
    for isomer_label in [0, 1]:

        us = torch.cat(adaptives[simulation][isomer_label]['us']).reshape(1000, 50, 1)
        cvs = cvss[simulation][isomer_label]
        
        time_slices = adaptives[simulation][isomer_label]['time_mcmc']
        time_flatten = [t for time_slice in time_slices for t in time_slice]
        time_min = min(time_flatten)
        time_mcmc = np.array([t - time_min for t in time_flatten])/3600

        rhat_info = torch.cat((cvs, us), dim=2).detach().numpy().transpose(1, 0, 2)

        rhat = R_hat(rhat_info, labels=['C', 'R', 'U'])

        df = pd.DataFrame(rhat[0], columns=['C', 'R', 'U'])
        df['Time (h)'] = time_mcmc[rhat[1]]
        df['MCMC step'] = rhat[1]
        df['Method'] = simulation
        df['Isomer'] = isomer_label

        rhat_df.append(df)

rhat_df = pd.concat(rhat_df)
rhat_df.to_csv(save_path + "/rhat.csv", index=False)        
rhat_df

,C,R,U,Time (h),MCMC step,Method,Isomer
0,1.210686,1.228267,1.194109,2.800454,90,ab-flowMC,0
1,1.121994,1.119943,1.107089,5.679586,180,ab-flowMC,0
2,1.065124,1.070826,1.065830,8.531614,270,ab-flowMC,0
3,1.042406,1.042423,1.055567,11.332435,360,ab-flowMC,0
4,1.029414,1.032330,1.040203,14.137912,450,ab-flowMC,0
5,1.028392,1.029847,1.033139,16.935509,540,ab-flowMC,0
6,1.021719,1.023650,1.026424,19.749465,630,ab-flowMC,0
7,1.018697,1.021742,1.021554,22.615388,720,ab-flowMC,0
8,1.017255,1.021114,1.017018,25.403506,810,ab-flowMC,0
9,1.016924,1.018331,1.016177,28.190027,900,ab-flowMC,0
0,1.217982,1.220970,1.161306,2.519394,90,ab-flowMC,1
1,1.100388,1.089410,1.073076,5.172716,180,ab-flowMC,1
2,1.059471,1.053101,1.043967,7.781391,270,ab-flowMC,1
3,1.048281,1.040696,1.032857,10.310547,360,ab-flowMC,1
4,1.029167,1.033462,1.028743,12.822650,450,ab-flowMC,1
5,1.022097,1.021740,1.025118,15.309495,540,ab-flowMC,1
6,1.020526,1.018749,1.026772,17.751451,630,ab-flowMC,1
7,1.021465,1.015853,1.025018,20.218419,720,ab-flowMC,1
8,1.022998,1.014829,1.023138,22.668880,810,ab-flowMC,1
9,1.021674,1.012816,1.022823,25.150480,900,ab-flowMC,1
0,1.073752,1.076108,1.068848,6.005644,90,ab-flowMC w.o. MLP,0
1,1.033209,1.035843,1.026413,12.095370,180,ab-flowMC w.o. MLP,0
2,1.018890,1.021973,1.017075,18.234401,270,ab-flowMC w.o. MLP,0
3,1.012753,1.016595,1.013818,24.464346,360,ab-flowMC w.o. MLP,0
4,1.010051,1.016697,1.012635,30.762989,450,ab-flowMC w.o. MLP,0
5,1.008116,1.017290,1.012385,37.140138,540,ab-flowMC w.o. MLP,0
6,1.007828,1.018780,1.013660,43.586530,630,ab-flowMC w.o. MLP,0
7,1.006568,1.018666,1.013277,50.078121,720,ab-flowMC w.o. MLP,0
8,1.004813,1.016503,1.013291,56.576279,810,ab-flowMC w.o. MLP,0
9,1.004333,1.016827,1.011660,63.027372,900,ab-flowMC w.o. MLP,0
0,1.055104,1.057816,1.048834,5.831300,90,ab-flowMC w.o. MLP,1
1,1.024184,1.023895,1.028001,11.652770,180,ab-flowMC w.o. MLP,1
2,1.015153,1.018667,1.015257,17.588274,270,ab-flowMC w.o. MLP,1
3,1.010869,1.010079,1.011136,23.639084,360,ab-flowMC w.o. MLP,1
4,1.009210,1.009258,1.008061,29.692424,450,ab-flowMC w.o. MLP,1
5,1.007665,1.008645,1.006944,35.744488,540,ab-flowMC w.o. MLP,1
6,1.006222,1.006496,1.005821,41.776382,630,ab-flowMC w.o. MLP,1
7,1.005105,1.005047,1.005498,47.835761,720,ab-flowMC w.o. MLP,1
8,1.004448,1.003910,1.004854,53.974674,810,ab-flowMC w.o. MLP,1
9,1.004303,1.003730,1.004087,60.042237,900,ab-flowMC w.o. MLP,1

## 1.d MLP datasets

In [87]:
mlp_datasets_df = []

simulation = simulation_types[method][0]

for isomer_label in [0, 1]:
    datasets = adaptives[simulation][isomer_label]['mlps_datasets']
    models = adaptives[simulation][isomer_label]['dict_mlps'][-1][0]['model']
    for key in ['train', 'test']:
        df = pd.DataFrame(columns=['Predictions', 'True values'])
    
        data = datasets[key][0].detach().numpy()
        predict = models(torch.tensor(data[:, :12]).float()).detach().numpy()

        df['True values'] = data[:, 12]
        df['Predictions'] = predict
        df['Isomer'] = isomer_label
        df['Dataset'] = key.capitalize()
        df['Method'] = simulation

        mlp_datasets_df.append(df)

mlp_datasets_df = pd.concat(mlp_datasets_df)
mlp_datasets_df.to_csv(save_path + "/mlp_datasets.csv", index=False)
print("MLP datasets saved to {:s}".format(save_path + "/mlp_datasets.csv"))

MLP datasets saved to /mnt/home/amolina/ceph/adaptive-flow-mc/figures/preprint_v2/data/mlp_datasets.csv

## 1.d Optical spectrum

# 2. Ab-flowMM

In [88]:
method, simulation_idxs[method].items()

('adaptive',
 dict_items([('ab-flowMC', {0: 31959916, 1: 31959919}), ('ab-flowMC w.o. MLP', {0: 31961552, 1: 31961553})]))

In [89]:
method = methods[1]

mixture_models = {}
cvs_mixture_models = {}

print("Loading data...")
for key, idx in simulation_idxs[method].items():
    print(key, idx)
    mixture_models[key] = load_pickle_file(get_simulation_filename_mm(idx), 
    simulations_folders[method][key])
    cvs_mixture_models[key] = load_pickle_file(get_cvs_filename_mm(idx),
    get_project_path())
    print("Loaded mixture model sampling {:s} and cvs and idx {:d}".format(
        key, idx))

Loading data...
ab-flowMM 32094541
Loaded mixture model sampling ab-flowMM and cvs and idx 32094541
ab-flowMM w.o. MLP 32094594
Loaded mixture model sampling ab-flowMM w.o. MLP and cvs and idx 32094594

## 2a. Acceptace rate

In [90]:
mixture_models.keys()

dict_keys(['ab-flowMM', 'ab-flowMM w.o. MLP'])

In [91]:
accs_df_mm = []

    
for key in mixture_models.keys():

    df = pd.DataFrame(columns=['Method', 'Isomer', 'Step', 'Acceptance Rate'])
    accs = mixture_models[key]['accs'].float().mean(dim=1).numpy()

    df['Acceptance Rate'] = accs
    df['Isomer'] = key
    df['Step'] = np.arange(0, len(accs))
    df['Method'] = key

    accs_df_mm.append(df)

accs_df_mm = pd.concat(accs_df_mm)
accs_df_mm.to_csv(save_path + "/acceptance_rates_mm.csv", index=False)
print("Acceptance rates saved to {:s}".format(save_path + "/acceptance_rates_mm.csv"))

Acceptance rates saved to /mnt/home/amolina/ceph/adaptive-flow-mc/figures/preprint_v2/data/acceptance_rates_mm.csv

In [92]:
accs_df_mm

                  Method              Isomer  Step  Acceptance Rate
0              ab-flowMM           ab-flowMM     0             0.45
1              ab-flowMM           ab-flowMM     1             0.25
2              ab-flowMM           ab-flowMM     2             0.30
3              ab-flowMM           ab-flowMM     3             0.40
4              ab-flowMM           ab-flowMM     4             0.30
...                  ...                 ...   ...              ...
2996  ab-flowMM w.o. MLP  ab-flowMM w.o. MLP  2996             0.25
2997  ab-flowMM w.o. MLP  ab-flowMM w.o. MLP  2997             0.30
2998  ab-flowMM w.o. MLP  ab-flowMM w.o. MLP  2998             0.50
2999  ab-flowMM w.o. MLP  ab-flowMM w.o. MLP  2999             0.45
3000  ab-flowMM w.o. MLP  ab-flowMM w.o. MLP  3000             0.45

[6002 rows x 4 columns]

## 2.b Collective variables

In [94]:
cvs_us_df_mm = []

for key in mixture_models.keys():

    us = mixture_models[key]['us'].reshape(3001, 20, 1)
    isomers = mixture_models[key]['isomers'].reshape(3001, 20, 1)
    cvs = cvs_mixture_models[key]
    cvs_us = torch.cat([us, cvs, isomers], dim=2).numpy().reshape(60020, 4)
    df = pd.DataFrame(cvs_us, columns=['U', 'C', 'R', 'Isomer'])
    df['Method'] = key
    cvs_us_df_mm.append(df)

cvs_us_df_mm = pd.concat(cvs_us_df_mm)
cvs_us_df_mm.to_csv(save_path + "/cvs_potential_energy_mm.csv", index=False)
print("CVs and potential energy saved to {:s}".format(save_path + "/cvs_potential_energy.csv"))
cvs_us_df

CVs and potential energy saved to /mnt/home/amolina/ceph/adaptive-flow-mc/figures/preprint_v2/data/cvs_potential_energy.csv

              U          C         R  Isomer              Method
0     -6.773585  10.105214  2.457276       0           ab-flowMC
1     -6.750111  10.205934  2.442652       0           ab-flowMC
2     -6.764058   9.652035  2.473082       0           ab-flowMC
3     -6.732985  10.172332  2.427748       0           ab-flowMC
4     -6.748763   9.293897  2.517407       0           ab-flowMC
...         ...        ...       ...     ...                 ...
49995 -6.704685  10.828248  2.220704       1  ab-flowMC w.o. MLP
49996 -6.746437  10.425041  2.232781       1  ab-flowMC w.o. MLP
49997 -6.714196  11.065727  2.218863       1  ab-flowMC w.o. MLP
49998 -6.743561  11.145951  2.213711       1  ab-flowMC w.o. MLP
49999 -6.659955  10.590937  2.276659       1  ab-flowMC w.o. MLP

[200000 rows x 5 columns]

## 2.c Rhat

In [95]:
mixture_models['ab-flowMM']['time_mcmc']

[1708189151.0943224,
 1708189174.2343788,
 1708189195.588432,
 1708189214.7881203,
 1708189234.200983,
 1708189258.52606,
 1708189281.175341,
 1708189303.967947,
 1708189327.502511,
 1708189349.9778516,
 1708189368.9729922,
 1708189390.6472232,
 1708189412.9873347,
 1708189436.6245706,
 1708189462.4731402,
 1708189485.3448074,
 1708189508.380226,
 1708189532.071178,
 1708189553.3794088,
 1708189576.5040863,
 1708189594.4745004,
 1708189619.405209,
 1708189640.1275144,
 1708189661.7312138,
 1708189689.228767,
 1708189709.1145444,
 1708189734.914357,
 1708189753.793246,
 1708189774.7511375,
 1708189801.594333,
 1708189819.8925445,
 1708189841.774198,
 1708189864.8293457,
 1708189883.103205,
 1708189906.264728,
 1708189930.2061539,
 1708189948.5213995,
 1708189967.9747782,
 1708189992.6623697,
 1708190010.445664,
 1708190034.2037446,
 1708190055.3663304,
 1708190076.0757465,
 1708190093.7077901,
 1708190113.6783462,
 1708190138.511592,
 1708190157.0238364,
 1708190185.494059,
 1708190204.1089017,
 1708190223.5465796,
 1708190241.7309763,
 1708190265.9296477,
 1708190287.2717965,
 1708190309.469434,
 1708190334.7004528,
 1708190354.9375486,
 1708190372.1562376,
 1708190391.1486018,
 1708190410.1264527,
 1708190437.23699,
 1708190457.2849631,
 1708190479.5601838,
 1708190500.603007,
 1708190525.989085,
 1708190545.4466977,
 1708190573.0116649,
 1708190592.5987794,
 1708190616.5397708,
 1708190642.0726392,
 1708190661.7851691,
 1708190681.1576648,
 1708190700.7318685,
 1708190720.0149353,
 1708190739.1257915,
 1708190756.600057,
 1708190780.5716288,
 1708190800.85634,
 1708190822.2983603,
 1708190848.2367918,
 1708190868.2574732,
 1708190886.1457813,
 1708190912.277329,
 1708190931.462248,
 1708190952.6095874,
 1708190972.8952188,
 1708190992.6763053,
 1708191011.3738377,
 1708191030.092584,
 1708191050.0634289,
 1708191067.8022568,
 1708191085.5352025,
 1708191105.920557,
 1708191123.7542183,
 1708191144.1361487,
 1708191165.64078,
 1708191185.2701643,
 1708191210.298129,
 1708191232.5521402,
 1708191250.5313134,
 1708191271.668772,
 1708191293.5066462,
 1708191400.3915882,
 1708191427.3986962,
 1708191447.8477468,
 1708191468.4554534,
 1708191488.5559132,
 1708191512.5835073,
 1708191534.0973988,
 1708191553.006819,
 1708191574.7017016,
 1708191594.801891,
 1708191613.165854,
 1708191635.8658233,
 1708191657.830021,
 1708191680.1071703,
 1708191702.7827706,
 1708191721.584895,
 1708191743.8080266,
 1708191764.3389375,
 1708191782.294505,
 1708191801.1875274,
 1708191824.4439507,
 1708191845.2315536,
 1708191864.73897,
 1708191883.5966241,
 1708191905.6885083,
 1708191928.8210883,
 1708191952.5771315,
 1708191972.4057117,
 1708191991.1638288,
 1708192015.7218268,
 1708192040.6250534,
 1708192059.551723,
 1708192079.6953802,
 1708192102.7854002,
 1708192124.8547332,
 1708192144.963331,
 1708192170.7456264,
 1708192189.7646735,
 1708192207.269405,
 1708192227.2339318,
 1708192247.273306,
 1708192267.1998851,
 1708192287.4549942,
 1708192314.8097856,
 1708192335.5846844,
 1708192356.4061508,
 1708192376.280082,
 1708192396.3144472,
 1708192417.9769397,
 1708192436.256097,
 1708192457.7041945,
 1708192477.8058822,
 1708192498.3318713,
 1708192515.7446237,
 1708192537.117399,
 1708192568.048848,
 1708192586.7755628,
 1708192605.3866472,
 1708192624.8545864,
 1708192644.4425275,
 1708192663.1481562,
 1708192681.7048757,
 1708192701.324355,
 1708192722.9231818,
 1708192743.081118,
 1708192767.9239364,
 1708192789.6409044,
 1708192809.3509226,
 1708192830.139805,
 1708192852.4790366,
 1708192869.354954,
 1708192889.124925,
 1708192905.7448277,
 1708192925.08415,
 1708192942.037063,
 1708192961.6010215,
 1708192980.1747203,
 1708192999.1824796,
 1708193018.3109145,
 1708193037.9756277,
 1708193057.8304243,
 1708193077.8827333,
 1708193095.5946393,
 1708193116.6056788,
 1708193136.4309077,
 1708193155.137202,
 1708193173.797624,
 1708193193.0898204,
 1708193211.272869,
 1708193232.0595849,
 1708193254.470159,
 1708193278.3848479,
 1708193299.1541271,
 1708193322.9767358,
 1708193350.5463655,
 1708193372.2374074,
 1708193391.7636528,
 1708193411.5980453,
 1708193431.9243245,
 1708193450.9780815,
 1708193560.477059,
 1708193580.9586608,
 1708193605.135617,
 1708193628.8976107,
 1708193647.8700418,
 1708193667.1270504,
 1708193686.080629,
 1708193708.5984926,
 1708193730.7817676,
 1708193750.6644166,
 1708193769.560996,
 1708193790.3919954,
 1708193810.722608,
 1708193827.6790116,
 1708193845.8552065,
 1708193870.0584896,
 1708193888.5593646,
 1708193906.954386,
 1708193924.340105,
 1708193943.8355827,
 1708193962.1552076,
 1708193984.2823904,
 1708194003.1866295,
 1708194022.889529,
 1708194041.8886194,
 1708194062.7344055,
 1708194083.6514583,
 1708194106.2468069,
 1708194127.7280724,
 1708194146.101953,
 1708194166.248111,
 1708194187.6942356,
 1708194207.4490228,
 1708194231.4034975,
 1708194251.1599262,
 1708194274.0470083,
 1708194295.959664,
 1708194316.1333578,
 1708194338.1304073,
 1708194366.4911988,
 1708194387.3866491,
 1708194412.2776399,
 1708194434.2551107,
 1708194453.715691,
 1708194474.48442,
 1708194501.1973717,
 1708194518.5980577,
 1708194536.8582442,
 1708194558.1697578,
 1708194577.9264555,
 1708194597.1882308,
 1708194615.0902584,
 1708194639.8024733,
 1708194659.272432,
 1708194679.6134348,
 1708194699.425399,
 1708194721.3905375,
 1708194741.7408824,
 1708194764.4771297,
 1708194787.9438605,
 1708194805.9976184,
 1708194824.3079522,
 1708194849.2869446,
 1708194866.8795478,
 1708194886.2441008,
 1708194907.1655467,
 1708194924.6152582,
 1708194942.5203285,
 1708194959.5368326,
 1708194979.684946,
 1708194999.5455704,
 1708195018.4196975,
 1708195042.1120298,
 1708195061.1037433,
 1708195080.4310718,
 1708195098.8146183,
 1708195118.3473618,
 1708195135.7991142,
 1708195153.423847,
 1708195174.7745085,
 1708195197.7357702,
 1708195219.196882,
 1708195237.1042504,
 1708195258.0091047,
 1708195277.5476992,
 1708195301.6964478,
 1708195319.5134723,
 1708195338.2412765,
 1708195355.3831155,
 1708195374.6737902,
 1708195393.609569,
 1708195412.4845164,
 1708195437.7540002,
 1708195461.5660808,
 1708195482.5888727,
 1708195505.6082318,
 1708195526.4148884,
 1708195545.1369255,
 1708195563.03073,
 1708195583.2647502,
 1708195693.293075,
 1708195719.1328816,
 1708195739.4206772,
 1708195758.7340918,
 1708195777.3556983,
 1708195798.2230973,
 1708195821.1629665,
 1708195842.2693377,
 1708195861.7691832,
 1708195881.2469854,
 1708195901.383031,
 1708195925.712768,
 1708195946.620851,
 1708195966.5706236,
 1708195988.5681407,
 1708196009.3389409,
 1708196031.5677202,
 1708196050.4503453,
 1708196077.6006117,
 1708196103.2151856,
 1708196127.4376702,
 1708196149.5372386,
 1708196167.4989314,
 1708196184.715602,
 1708196203.4726813,
 1708196225.6941962,
 1708196247.183449,
 1708196274.2744257,
 1708196297.242196,
 1708196317.022909,
 1708196338.0433378,
 1708196360.5903957,
 1708196382.0373595,
 1708196408.7734861,
 1708196429.6647263,
 1708196449.4091508,
 1708196467.2991292,
 1708196490.1868706,
 1708196510.6905754,
 1708196530.4359803,
 1708196554.0871055,
 1708196572.7157233,
 1708196593.2125895,
 1708196610.7134624,
 1708196628.214077,
 1708196647.6650717,
 1708196671.683997,
 1708196693.9193218,
 1708196713.511492,
 1708196732.455816,
 1708196760.5472996,
 1708196782.70511,
 1708196807.4440243,
 1708196826.9727323,
 1708196846.012235,
 1708196864.1231575,
 1708196885.2567494,
 1708196906.566803,
 1708196926.934858,
 1708196951.1342618,
 1708196971.82511,
 1708196992.5787337,
 1708197015.7511933,
 1708197036.8843634,
 1708197060.9452016,
 1708197086.5458462,
 1708197104.7911217,
 1708197129.1655562,
 1708197153.5936227,
 1708197175.8366694,
 1708197198.718317,
 1708197219.5829556,
 1708197238.7925522,
 1708197262.5159254,
 1708197282.1417959,
 1708197301.140027,
 1708197320.7323537,
 1708197339.170183,
 1708197360.786383,
 1708197386.4908895,
 1708197405.7061,
 1708197429.5854373,
 1708197446.7873995,
 1708197464.972917,
 1708197483.6307786,
 1708197502.5691404,
 1708197520.8590958,
 1708197541.3485894,
 1708197560.1106496,
 1708197577.53937,
 1708197599.2472339,
 1708197620.484261,
 1708197646.6961064,
 1708197668.6408753,
 1708197689.2674184,
 1708197713.2829022,
 1708197737.367144,
 1708197759.4004655,
 1708197776.4089704,
 1708197796.6765234,
 1708197909.5242574,
 1708197930.317712,
 1708197949.1212997,
 1708197968.3260105,
 1708197988.8296812,
 1708198007.1069179,
 1708198026.5942452,
 1708198045.9047756,
 1708198066.0528638,
 1708198086.661144,
 1708198111.434655,
 1708198132.2194543,
 1708198152.8835428,
 1708198171.7100265,
 1708198192.9740262,
 1708198211.4315774,
 1708198234.947742,
 1708198259.1196263,
 1708198277.3897777,
 1708198296.9513474,
 1708198317.6791735,
 1708198340.3290083,
 1708198358.8126154,
 1708198382.239671,
 1708198401.1013474,
 1708198422.4239714,
 1708198446.7006822,
 1708198467.3032813,
 1708198484.3410032,
 1708198502.4256418,
 1708198523.204923,
 1708198540.1412153,
 1708198557.7213063,
 1708198574.9560869,
 1708198596.7265294,
 1708198614.7751174,
 1708198635.761983,
 1708198655.279552,
 1708198679.0779812,
 1708198698.206108,
 1708198724.1222584,
 1708198745.5837898,
 1708198769.282884,
 1708198793.2379115,
 1708198815.5898964,
 1708198837.4845967,
 1708198858.2613246,
 1708198880.1015315,
 1708198909.378922,
 1708198928.015222,
 1708198945.5516906,
 1708198962.9964783,
 1708198988.1747262,
 1708199010.0854166,
 1708199028.2477279,
 1708199047.121554,
 1708199064.94799,
 1708199082.876457,
 1708199104.094305,
 1708199121.4984987,
 1708199139.884428,
 1708199162.7452438,
 1708199185.6366878,
 1708199209.403466,
 1708199228.9523282,
 1708199247.0051184,
 1708199268.9247594,
 1708199296.5237288,
 1708199317.5928557,
 1708199342.386813,
 1708199361.677495,
 1708199379.7718832,
 1708199402.104172,
 1708199419.4838767,
 1708199437.1285279,
 1708199454.8361304,
 1708199472.3592467,
 1708199494.9394798,
 1708199513.2706149,
 1708199532.009344,
 1708199551.0488045,
 1708199577.4067292,
 1708199597.656822,
 1708199616.8231058,
 1708199636.2696173,
 1708199660.354035,
 1708199680.4173486,
 1708199698.4170194,
 1708199720.8091288,
 1708199743.5722852,
 1708199763.8880363,
 1708199786.5175383,
 1708199810.402696,
 1708199828.3264313,
 1708199848.7074962,
 1708199867.714824,
 1708199894.4566436,
 1708199913.93989,
 1708199932.7694407,
 1708199958.2381465,
 1708200080.7733579,
 1708200098.0653634,
 1708200121.9611323,
 1708200142.024677,
 1708200160.9176316,
 1708200180.0125754,
 1708200199.0503316,
 1708200223.622722,
 1708200242.506533,
 1708200264.1261165,
 1708200282.1906312,
 1708200300.50221,
 1708200318.3477857,
 1708200336.8839114,
 1708200354.270643,
 1708200378.1747634,
 1708200396.0419433,
 1708200417.2297373,
 1708200439.0576763,
 1708200459.8646657,
 1708200478.0578852,
 1708200497.0710444,
 1708200517.2581396,
 1708200539.1570842,
 1708200558.0056543,
 1708200585.5975578,
 1708200603.567191,
 1708200624.085872,
 1708200643.8599339,
 1708200664.0293684,
 1708200689.2151933,
 1708200710.9139376,
 1708200730.8934512,
 1708200752.1124423,
 1708200773.3810203,
 1708200795.3901637,
 1708200813.0824869,
 1708200832.228228,
 1708200851.0456932,
 1708200871.1202533,
 1708200890.5835352,
 1708200908.2159421,
 1708200932.4498518,
 1708200954.09622,
 1708200974.5537102,
 1708200994.2288904,
 1708201015.0831103,
 1708201034.2442596,
 1708201058.946278,
 1708201079.5869346,
 1708201097.5175674,
 1708201115.5250957,
 1708201134.431787,
 1708201154.8210168,
 1708201179.1874325,
 1708201197.138258,
 1708201218.0313087,
 1708201236.5350256,
 1708201255.177095,
 1708201273.566391,
 1708201294.6143396,
 1708201318.0565681,
 1708201338.0055132,
 1708201357.030227,
 1708201380.1100824,
 1708201398.571855,
 1708201418.1594481,
 1708201444.7237298,
 1708201467.7444274,
 1708201487.7151146,
 1708201509.1854866,
 1708201533.0560575,
 1708201553.9996426,
 1708201570.7330904,
 1708201588.8228834,
 1708201609.3318965,
 1708201632.6514332,
 1708201656.5973096,
 1708201674.6536741,
 1708201694.080172,
 1708201713.035743,
 1708201731.670095,
 1708201750.5232098,
 1708201767.4978976,
 1708201785.704801,
 1708201806.1072302,
 1708201826.5774722,
 1708201846.2452803,
 1708201866.0854216,
 1708201883.1171103,
 1708201901.4958935,
 1708201919.9442816,
 1708201937.2870858,
 1708201961.633419,
 1708201987.877145,
 1708202008.2253342,
 1708202032.694853,
 1708202053.1241283,
 1708202072.9383793,
 1708202092.78819,
 1708202214.482197,
 1708202239.23582,
 1708202258.7352755,
 1708202277.1602864,
 1708202302.3952339,
 1708202322.137382,
 1708202345.8289552,
 1708202368.9214284,
 1708202387.6936998,
 1708202405.8292685,
 1708202429.2734017,
 1708202453.4291017,
 1708202479.429162,
 1708202502.865433,
 1708202526.8023655,
 1708202545.3291688,
 1708202564.8949597,
 1708202587.9218578,
 1708202605.194546,
 1708202624.4511738,
 1708202645.6344323,
 1708202664.237182,
 1708202683.3751817,
 1708202710.7389956,
 1708202731.0704036,
 1708202750.9562378,
 1708202770.4693265,
 1708202790.989545,
 1708202814.1554534,
 1708202832.1301343,
 1708202859.835889,
 1708202879.1044116,
 1708202898.6460533,
 1708202918.8677719,
 1708202942.3940766,
 1708202962.8026018,
 1708202981.2193277,
 1708203007.4900608,
 1708203031.9078085,
 1708203049.997437,
 1708203068.3430097,
 1708203087.6730871,
 1708203109.2012572,
 1708203131.0269651,
 1708203157.0409772,
 1708203177.4539094,
 1708203200.9896257,
 1708203217.674075,
 1708203236.769456,
 1708203254.9016168,
 1708203286.2380793,
 1708203304.304105,
 1708203326.9452055,
 1708203345.0067127,
 1708203364.9946969,
 1708203382.7465262,
 1708203399.897119,
 1708203421.2372289,
 1708203443.2485747,
 1708203461.504338,
 1708203482.2515912,
 1708203501.3367891,
 1708203526.5863903,
 1708203546.0898695,
 1708203566.9533584,
 1708203587.7874577,
 1708203613.1669295,
 1708203634.7150369,
 1708203658.505741,
 1708203678.591794,
 1708203702.853117,
 1708203725.576336,
 1708203742.9808524,
 1708203768.7972374,
 1708203788.621089,
 1708203812.7241917,
 1708203835.9519572,
 1708203863.3279746,
 1708203888.7431302,
 1708203907.7188632,
 1708203933.7612467,
 1708203952.868949,
 1708203972.6696138,
 1708203991.3273423,
 1708204009.9496965,
 1708204035.3412726,
 1708204053.7248359,
 1708204073.2613308,
 1708204097.0164163,
 1708204117.4048693,
 1708204136.760975,
 1708204155.4368277,
 1708204179.624349,
 1708204203.0632,
 1708204224.0337565,
 1708204243.187264,
 1708204261.8437982,
 1708204281.1764216,
 1708204305.799418,
 1708204326.4709818,
 1708204452.5673842,
 1708204473.5205462,
 1708204497.407385,
 1708204522.7265444,
 1708204542.3544674,
 1708204562.6231585,
 1708204580.1802566,
 1708204600.3348796,
 1708204617.7290998,
 1708204635.7568982,
 1708204652.7623537,
 1708204672.6391957,
 1708204692.8213782,
 1708204717.8342812,
 1708204736.560953,
 1708204757.807876,
 1708204781.473572,
 1708204801.4296756,
 1708204820.48153,
 1708204838.8187559,
 1708204857.3466928,
 1708204877.0845325,
 1708204895.829534,
 1708204917.4218307,
 1708204937.0050383,
 1708204956.996045,
 1708204980.3025227,
 1708205001.2326078,
 1708205022.12097,
 1708205039.6861851,
 1708205056.4965312,
 1708205075.561909,
 1708205100.1330273,
 1708205126.5173542,
 1708205144.9651864,
 1708205164.8591945,
 1708205184.0838296,
 1708205204.622811,
 1708205225.6894436,
 1708205248.688307,
 1708205271.5782728,
 1708205288.6152167,
 1708205308.0354903,
 1708205331.4079936,
 1708205354.6440604,
 1708205375.8712165,
 1708205396.2985544,
 1708205418.464886,
 1708205439.9493866,
 1708205459.456854,
 1708205484.4517045,
 1708205505.9647007,
 1708205526.5042293,
 1708205546.2277336,
 1708205566.5302796,
 1708205585.2098074,
 1708205608.1248007,
 1708205626.876304,
 1708205646.6482112,
 1708205667.106689,
 1708205694.5650551,
 1708205713.1349294,
 1708205732.4238715,
 1708205753.4766557,
 1708205772.42394,
 1708205790.5757508,
 1708205809.7982016,
 1708205834.506335,
 1708205852.38086,
 1708205875.631279,
 1708205894.4153469,
 1708205914.4043734,
 1708205933.3737485,
 1708205956.938033,
 1708205976.8198173,
 1708205998.8681629,
 1708206018.4046159,
 1708206036.9182959,
 1708206056.0502186,
 1708206076.8420424,
 1708206101.750537,
 1708206122.622766,
 1708206147.109744,
 1708206165.7416928,
 1708206187.0543828,
 1708206203.6975262,
 1708206223.0704749,
 1708206244.208903,
 1708206268.9822814,
 1708206290.9407854,
 1708206315.7962942,
 1708206334.8124983,
 1708206353.16714,
 1708206373.7353632,
 1708206393.7697902,
 1708206416.1102872,
 1708206436.7467408,
 1708206457.6945593,
 1708206474.9394245,
 1708206497.2146578,
 1708206639.6376925,
 1708206659.564933,
 1708206685.0961835,
 1708206706.7392874,
 1708206724.5089743,
 1708206744.3088036,
 1708206763.8083131,
 1708206786.2081647,
 1708206806.382452,
 1708206823.4356124,
 1708206842.8916047,
 1708206860.22888,
 1708206878.86255,
 1708206897.747255,
 1708206916.3096256,
 1708206941.4523454,
 1708206965.267676,
 1708206983.3514285,
 1708207002.2666466,
 1708207022.830998,
 1708207047.5693593,
 1708207065.8214784,
 1708207083.611236,
 1708207101.354497,
 1708207126.6398427,
 1708207146.2833564,
 1708207166.304332,
 1708207188.509362,
 1708207207.408884,
 1708207226.909405,
 1708207245.9764113,
 1708207266.4181538,
 1708207290.0587807,
 1708207317.505605,
 1708207344.6685057,
 1708207363.9971678,
 1708207387.0285842,
 1708207404.9620218,
 1708207428.2508667,
 1708207448.414493,
 1708207468.8077176,
 1708207492.2452214,
 1708207517.2857423,
 1708207537.650452,
 1708207558.9564624,
 1708207576.797735,
 1708207595.9864364,
 1708207615.8939269,
 1708207632.4175735,
 1708207653.1956778,
 1708207670.0551798,
 1708207693.4460487,
 1708207713.1298625,
 1708207732.9872556,
 1708207751.890636,
 1708207772.6416187,
 1708207790.398217,
 1708207808.8425617,
 1708207831.052989,
 1708207852.2418983,
 1708207874.576597,
 1708207894.6811643,
 1708207919.5658126,
 1708207938.2735238,
 1708207957.204455,
 1708207976.4950109,
 1708207993.4108114,
 1708208021.6408527,
 1708208042.7228842,
 1708208061.6394649,
 1708208080.1063442,
 1708208098.8898225,
 1708208117.013976,
 1708208135.3569372,
 1708208158.9596217,
 1708208178.777063,
 1708208204.6556857,
 1708208227.1782403,
 1708208245.903559,
 1708208266.7774699,
 1708208291.2403257,
 1708208309.5128024,
 1708208333.1920228,
 1708208353.497254,
 1708208380.8473828,
 1708208400.5789917,
 1708208424.2883132,
 1708208444.3385615,
 1708208469.492205,
 1708208488.662493,
 1708208508.4574232,
 1708208525.7239943,
 1708208545.2583807,
 1708208562.44114,
 1708208582.0618796,
 1708208601.087761,
 1708208621.6274745,
 1708208648.2504709,
 1708208665.7974718,
 1708208688.7809587,
 1708208828.7369,
 1708208849.3065257,
 1708208871.3307812,
 1708208892.8524551,
 1708208920.34399,
 1708208941.6893747,
 1708208959.4948597,
 1708208979.5713959,
 1708208998.4800875,
 1708209017.5526352,
 1708209040.526283,
 1708209064.7627177,
 1708209082.772668,
 1708209100.6250918,
 1708209120.1150157,
 1708209141.592642,
 1708209162.6623268,
 1708209190.273549,
 1708209210.248319,
 1708209228.7548234,
 1708209246.598596,
 1708209264.5112917,
 1708209288.378805,
 1708209307.273541,
 1708209325.9702322,
 1708209348.0676877,
 1708209366.2316716,
 1708209385.898485,
 1708209405.3988943,
 1708209424.856269,
 1708209448.566717,
 1708209470.1400013,
 1708209490.3377168,
 1708209509.9063535,
 1708209528.750398,
 1708209547.9592092,
 1708209573.6683474,
 1708209591.5118816,
 1708209611.3484929,
 1708209632.7542655,
 1708209653.213355,
 1708209672.6124856,
 1708209695.2167659,
 1708209715.4388473,
 1708209734.4048896,
 1708209753.8921044,
 1708209776.4433308,
 1708209798.0270607,
 1708209817.958268,
 1708209840.259303,
 1708209856.793135,
 1708209876.6534917,
 1708209896.8003469,
 1708209916.2766116,
 1708209938.5813854,
 1708209959.1332493,
 1708209978.5966961,
 1708209998.5935338,
 1708210018.0726154,
 1708210042.803484,
 1708210064.2503185,
 1708210086.0213726,
 1708210107.583286,
 1708210131.67761,
 1708210155.1890786,

In [97]:
rhat_df_mm = []

for key in mixture_models.keys():

    us = mixture_models[key]['us'].reshape(3001, 20, 1)
    cvs = cvs_mixture_models[key]
    
    time_mm = mixture_models[key]['time_mcmc']
    time_min = min(time_mm)
    time_mcmc = np.array([t - time_min for t in time_mm])/3600

    rhat_info = torch.cat((cvs, us), dim=2).detach().numpy().transpose(1, 0, 2)

    rhat = R_hat(rhat_info, labels=['C', 'R', 'U'])

    df = pd.DataFrame(rhat[0], columns=['C', 'R', 'U'])
    df['Time (h)'] = time_mcmc[rhat[1]]
    df['MCMC step'] = rhat[1]
    df['Method'] = key

    rhat_df_mm.append(df)

rhat_df_mm = pd.concat(rhat_df_mm)
rhat_df_mm.to_csv(save_path + "/rhat.csv", index=False)        
rhat_df_mm

          C         R         U   Time (h)  MCMC step              Method
0  1.244847  1.203371  1.201282   1.728772        290           ab-flowMM
1  1.221467  1.188414  1.174443   3.484163        580           ab-flowMM
2  1.130501  1.171119  1.089868   5.252929        870           ab-flowMM
3  1.101117  1.171875  1.096969   7.032640       1160           ab-flowMM
4  1.085846  1.177203  1.099640   8.837655       1450           ab-flowMM
5  1.085960  1.175499  1.074861  10.671688       1740           ab-flowMM
6  1.080660  1.156738  1.070799  12.524613       2030           ab-flowMM
7  1.081210  1.160547  1.075155  14.406494       2320           ab-flowMM
8  1.079550  1.164322  1.074507  16.304235       2610           ab-flowMM
9  1.078325  1.156593  1.064598  18.301156       2901           ab-flowMM
0  1.069036  1.085608  1.054484   8.396770        290  ab-flowMM w.o. MLP
1  1.043829  1.076288  1.036531  16.760332        580  ab-flowMM w.o. MLP
2  1.034084  1.087874  1.054805  25.147409        870  ab-flowMM w.o. MLP
3  1.022466  1.074202  1.048505  33.485120       1160  ab-flowMM w.o. MLP
4  1.017431  1.046758  1.028940  41.887548       1450  ab-flowMM w.o. MLP
5  1.017717  1.025231  1.021978  50.382101       1740  ab-flowMM w.o. MLP
6  1.017207  1.025405  1.017583  58.806390       2030  ab-flowMM w.o. MLP
7  1.018809  1.028063  1.019071  67.200279       2320  ab-flowMM w.o. MLP
8  1.020713  1.030620  1.018449  75.645447       2610  ab-flowMM w.o. MLP
9  1.018734  1.024812  1.020375  84.122752       2901  ab-flowMM w.o. MLP

# 2.d Isomers

In [101]:
isomers_jumps = []

for key in mixture_models.keys():
    
    isomers = mixture_models[key]['isomers'].int()#.reshape(3001, 20, 1)

    df = pd.DataFrame(isomers, columns=['chain {:d}'.format(i) for i in np.arange(20)])
    df['Step'] = np.arange(0, 3001)
    df['Method'] = key
    
    isomers_jumps.append(df)

isomers_jumps = pd.concat(isomers_jumps)
isomers_jumps.to_csv(save_path + "/isomers_jumps_mm.csv", index=False)
print("Isomers jumps saved to {:s}".format(save_path + "/isomers_jumps_mm.csv"))

## 2.e Populations