In [68]:
import warnings
warnings.filterwarnings("ignore")

In [69]:
import os
import torch
import numpy as np
import pandas as pd

from flonacomldft.utils.io_utils import (
    load_pickle_file,
    get_project_path
)

from flonacomldft.internal_coordinates import (
    Coordinates_mapping
)

from flonacomldft.utils.diagnostics import R_hat

# 1. Ab-flowMC simulations

In [70]:
simulation_types = ['ab-flowMC', 'ab-flowMC w.o. MLP']

In [71]:
simulation_idxs = { simulation_types[0]: {
                        0: 31959916,
                        1: 31959919
                    },

                    simulation_types[1]: {
                        0: 31961552,
                        1: 31961553
                    }
                }

In [72]:
simulations_folders = {
    simulation_types[0]: get_project_path() + "/2-adaptive-mlp",
    simulation_types[1]: get_project_path() + "/1-adaptive"
}

save_path = get_project_path() + "/figures/preprint_v2/data"

In [73]:
get_simulation_filename = lambda isomer_label, idx: "results_adaptive_is{:d}_{:d}/adaptive_sampling_is{:d}_{:d}.pkl".format(
    isomer_label, idx, isomer_label, idx)
get_cvs_filename = lambda isomer_label, idx: "results_adaptive_is{:d}_{:d}/cvs_is{:d}_{:d}.pkl".format(
    isomer_label, idx, isomer_label, idx)

In [74]:
adaptives = {}
cvss = {}

print("Loading data...")
for simulation in simulation_types:
    adaptives[simulation] = {}
    cvss[simulation] = {}
    for key, idx in simulation_idxs[simulation].items():
        adaptives[simulation][key] = load_pickle_file(get_simulation_filename(key, idx), 
        simulations_folders[simulation])
        cvss[simulation][key] = load_pickle_file(get_cvs_filename(key, idx),
        simulations_folders[simulation])
        print("Loaded adaptive sampling {:s} and cvs for isomer {:d} and idx {:d}".format(
            simulation, key, idx))

Loading data...

Loaded adaptive sampling ab-flowMC and cvs for isomer 0 and idx 31959916
Loaded adaptive sampling ab-flowMC and cvs for isomer 1 and idx 31959919
Loaded adaptive sampling ab-flowMC w.o. MLP and cvs for isomer 0 and idx 31961552
Loaded adaptive sampling ab-flowMC w.o. MLP and cvs for isomer 1 and idx 31961553

In [75]:
adaptive = adaptives[simulation_types[0]][0]

## 1.a Acceptance rate

In [76]:
accs_df = []

for simulation in simulation_types:
    
    for key, idx in simulation_idxs[simulation].items():

        df = pd.DataFrame(columns=['Method', 'Isomer', 'Step', 'Acceptance Rate'])
        accs = torch.cat(adaptives[simulation][key]['accs']).float().mean(dim=1).numpy()

        df['Acceptance Rate'] = accs
        df['Isomer'] = key
        df['Step'] = np.arange(0, len(accs))
        df['Method'] = simulation

        accs_df.append(df)

accs_df = pd.concat(accs_df)
accs_df.to_csv(save_path + "/acceptance_rates.csv", index=False)
print("Acceptance rates saved to {:s}".format(save_path + "/acceptance_rates.csv"))

Acceptance rates saved to /mnt/home/amolina/ceph/adaptive-flow-mc/figures/preprint_v2/data/acceptance_rates.csv

## 1.a Collective variables and Potential energy

In [77]:
cvs_us_df = []

for simulation in simulation_types:
    for isomer_label in [0, 1]:

        us = torch.cat(adaptives[simulation][isomer_label]['us']).reshape(1000, 50, 1)
        cvs = cvss[simulation][isomer_label]

        cvs_us = torch.cat([us, cvs], dim=2).numpy().reshape(50000, 3)

        df = pd.DataFrame(cvs_us, columns=['C', 'R', 'U'])
        df['Isomer'] = isomer_label
        df['Method'] = simulation

        cvs_us_df.append(df)

cvs_us_df = pd.concat(cvs_us_df)
cvs_us_df.to_csv(save_path + "/cvs_potential_energy.csv", index=False)
print("CVs and potential energy saved to {:s}".format(save_path + "/cvs_potential_energy.csv"))
cvs_us_df

CVs and potential energy saved to /mnt/home/amolina/ceph/adaptive-flow-mc/figures/preprint_v2/data/cvs_potential_energy.csv

              C          R         U  Isomer              Method
0     -6.773585  10.105214  2.457276       0           ab-flowMC
1     -6.750111  10.205934  2.442652       0           ab-flowMC
2     -6.764058   9.652035  2.473082       0           ab-flowMC
3     -6.732985  10.172332  2.427748       0           ab-flowMC
4     -6.748763   9.293897  2.517407       0           ab-flowMC
...         ...        ...       ...     ...                 ...
49995 -6.704685  10.828248  2.220704       1  ab-flowMC w.o. MLP
49996 -6.746437  10.425041  2.232781       1  ab-flowMC w.o. MLP
49997 -6.714196  11.065727  2.218863       1  ab-flowMC w.o. MLP
49998 -6.743561  11.145951  2.213711       1  ab-flowMC w.o. MLP
49999 -6.659955  10.590937  2.276659       1  ab-flowMC w.o. MLP

[200000 rows x 5 columns]

# Rhat

In [78]:
#isomer_label = 0
#simulation = simulation_types[0]

rhat_df = []

for simulation in simulation_types:
    for isomer_label in [0, 1]:

        us = torch.cat(adaptives[simulation][isomer_label]['us']).reshape(1000, 50, 1)
        cvs = cvss[simulation][isomer_label]
        
        time_slices = adaptives[simulation][isomer_label]['time_mcmc']
        time_flatten = [t for time_slice in time_slices for t in time_slice]
        time_min = min(time_flatten)
        time_mcmc = np.array([t - time_min for t in time_flatten])/3600

        rhat_info = torch.cat((cvs, us), dim=2).detach().numpy().transpose(1, 0, 2)

        rhat = R_hat(rhat_info, labels=['C', 'R', 'U'])

        df = pd.DataFrame(rhat[0], columns=['C', 'R', 'U'])
        df['Time (h)'] = time_mcmc[rhat[1]]
        df['MCMC step'] = rhat[1]
        df['Method'] = simulation
        df['Isomer'] = isomer_label

        rhat_df.append(df)

rhat_df = pd.concat(rhat_df)
rhat_df.to_csv(save_path + "/rhat.csv", index=False)        
rhat_df

,C,R,U,Time (h),MCMC step,Method,Isomer
0,1.210686,1.228267,1.194109,2.800454,90,ab-flowMC,0
1,1.121994,1.119943,1.107089,5.679586,180,ab-flowMC,0
2,1.065124,1.070826,1.065830,8.531614,270,ab-flowMC,0
3,1.042406,1.042423,1.055567,11.332435,360,ab-flowMC,0
4,1.029414,1.032330,1.040203,14.137912,450,ab-flowMC,0
5,1.028392,1.029847,1.033139,16.935509,540,ab-flowMC,0
6,1.021719,1.023650,1.026424,19.749465,630,ab-flowMC,0
7,1.018697,1.021742,1.021554,22.615388,720,ab-flowMC,0
8,1.017255,1.021114,1.017018,25.403506,810,ab-flowMC,0
9,1.016924,1.018331,1.016177,28.190027,900,ab-flowMC,0
0,1.217982,1.220970,1.161306,2.519394,90,ab-flowMC,1
1,1.100388,1.089410,1.073076,5.172716,180,ab-flowMC,1
2,1.059471,1.053101,1.043967,7.781391,270,ab-flowMC,1
3,1.048281,1.040696,1.032857,10.310547,360,ab-flowMC,1
4,1.029167,1.033462,1.028743,12.822650,450,ab-flowMC,1
5,1.022097,1.021740,1.025118,15.309495,540,ab-flowMC,1
6,1.020526,1.018749,1.026772,17.751451,630,ab-flowMC,1
7,1.021465,1.015853,1.025018,20.218419,720,ab-flowMC,1
8,1.022998,1.014829,1.023138,22.668880,810,ab-flowMC,1
9,1.021674,1.012816,1.022823,25.150480,900,ab-flowMC,1
0,1.073752,1.076108,1.068848,6.005644,90,ab-flowMC w.o. MLP,0
1,1.033209,1.035843,1.026413,12.095370,180,ab-flowMC w.o. MLP,0
2,1.018890,1.021973,1.017075,18.234401,270,ab-flowMC w.o. MLP,0
3,1.012753,1.016595,1.013818,24.464346,360,ab-flowMC w.o. MLP,0
4,1.010051,1.016697,1.012635,30.762989,450,ab-flowMC w.o. MLP,0
5,1.008116,1.017290,1.012385,37.140138,540,ab-flowMC w.o. MLP,0
6,1.007828,1.018780,1.013660,43.586530,630,ab-flowMC w.o. MLP,0
7,1.006568,1.018666,1.013277,50.078121,720,ab-flowMC w.o. MLP,0
8,1.004813,1.016503,1.013291,56.576279,810,ab-flowMC w.o. MLP,0
9,1.004333,1.016827,1.011660,63.027372,900,ab-flowMC w.o. MLP,0
0,1.055104,1.057816,1.048834,5.831300,90,ab-flowMC w.o. MLP,1
1,1.024184,1.023895,1.028001,11.652770,180,ab-flowMC w.o. MLP,1
2,1.015153,1.018667,1.015257,17.588274,270,ab-flowMC w.o. MLP,1
3,1.010869,1.010079,1.011136,23.639084,360,ab-flowMC w.o. MLP,1
4,1.009210,1.009258,1.008061,29.692424,450,ab-flowMC w.o. MLP,1
5,1.007665,1.008645,1.006944,35.744488,540,ab-flowMC w.o. MLP,1
6,1.006222,1.006496,1.005821,41.776382,630,ab-flowMC w.o. MLP,1
7,1.005105,1.005047,1.005498,47.835761,720,ab-flowMC w.o. MLP,1
8,1.004448,1.003910,1.004854,53.974674,810,ab-flowMC w.o. MLP,1
9,1.004303,1.003730,1.004087,60.042237,900,ab-flowMC w.o. MLP,1

In [79]:
#